{
 "title": "JVM Overview (Micrometer OTLP)",
 "description": "Dashboard for JVM metrics with Spring Boot OTLP metric exporter",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java",
  "otel",
  "opentelemetry",
  "otlp",
  "Spring",
  "Boot",
  "Spring Boot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(jvm_class_loaded_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_class_loaded_total{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Request rate of HTTP server requests",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "description": "Ratio of HTTP server requests that have returned a 5xx error code",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (instance)(rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", http_response_status_code!~\"2..\"}[5m]))) / on (instance) (sum by (instance)(rate(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "95% percentile of HTTP server request duration ",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum by(le, instance) (rate(http_server_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\"}[5m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the whole system",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_time_seconds_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Utilization",
   "type": "timeseries",
   "description": "How much of the available heap memory is used",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{job=~\"$job\",jvm_memory_type=\"heap\", instance=~\"$instance\"}) / on(instance) sum by (instance) (jvm_memory_limit_bytes{job=~\"$job\",jvm_memory_type=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Percentage of pause time spend for garbage collection pauses",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(jvm_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "description": "Number of currently loaded classes",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_class_loaded_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of currently executing (also called \"live\") threads (both daemon and non-daemon)",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jvm_thread_count{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}