services:
  api:
    image: todo-api:1.0
    ports:
      - "8585:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4317
    depends_on:
      - mongodb
      - lgtm
  mongodb:
    image: mongo
  lgtm:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
